# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Problem', models.TextField(max_length=2000)),
                ('Prescription', models.TextField(max_length=500)),
                ('Maternity_Services', models.TextField(max_length=1000)),
                ('Lab_Results', models.TextField(max_length=1000)),
                ('Ward_Report', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_No', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=40)),
                ('Faculty', models.CharField(max_length=40)),
                ('Department', models.CharField(max_length=40)),
                ('Course', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='Student_Information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student_Database'),
        ),
    ]
