# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_database',
            name='Student_Pic',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
