# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_database_student_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_database',
            name='Student_Pic',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
    ]
