# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161221_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_database',
            old_name='Student_Pic',
            new_name='Image',
        ),
    ]
