# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170103_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_database',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
