# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170103_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='Student_Name',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
