# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_records_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='Lab_Results',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='Maternity_Services',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='Prescription',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='records',
            name='Problem',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='Ward_Report',
            field=models.TextField(max_length=100),
        ),
    ]
